export const OFFER_CREATION_PENDING = 'REGISTRATION_FULFILLED';
export const OFFER_CREATION_FULFILLED = 'REGISTRATION_PENDING';
export const OFFER_CREATION_REJECTED = 'REGISTRATION_REJECTED';

export const GET_OFFERS_PENDING = 'GET_OFFERS_PENDING';
export const GET_OFFERS_FULFILLED = 'GET_OFFERS_FULFILLED';
export const GET_OFFERS_REJECTED = 'GET_OFFERS_REJECTED';
